---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: docs/README.md
  label: 首页
- type: directory
  path: docs/views/frontEnd
  label: blog-frontEnd
  create: all
  match: "**/*"
- type: directory
  path: docs/views
  label: blog
  create: all
  match: "**/*"
upload_dir: docs/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_command: vuvuepress build docs
  publish_command: vuepress build -d .vuepress/dist
  preview_output_directory: public
  output_directory: ".vuepress/dist"
  instant_preview_command: vuepress dev -p 8080 -h 0.0.0.0
